2019-06-11 17:23:07,575 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2019-06-12 15:30:18,228 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005//'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL // not found
2019-06-12 15:30:37,040 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/webhook/'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /webhook/ not found
2019-06-12 15:31:08,195 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2019-06-12 15:31:17,801 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2019-06-12 15:32:03,098 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2019-06-12 15:32:59,356 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005//version'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/chatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL //version not found
2019-07-04 11:11:34,790 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/run.py", line 180, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(nlu_model, endpoints.nlu)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 45, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 246, in __init__
    self._load_interpreter()
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 264, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/model.py", line 302, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/model.py", line 329, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/components.py", line 433, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/registry.py", line 181, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/utils/spacy_utils.py", line 130, in load
    nlp = cls.load_model(model_name)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/utils/spacy_utils.py", line 47, in load_model
    return spacy.load(spacy_model_name, disable=["parser"])
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 129, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 146, in load_model_from_link
    return cls.load(**overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 190, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 173, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/language.py", line 791, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 630, in from_disk
    reader(path / key)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/language.py", line 780, in <lambda>
    deserializers["vocab"] = lambda p: self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self)
  File "vocab.pyx", line 453, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 431, in spacy.vectors.Vectors.from_disk
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 625, in from_disk
    def from_disk(path, readers, exclude):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2019-07-04 11:26:04,316 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/run.py", line 180, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(nlu_model, endpoints.nlu)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 45, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 246, in __init__
    self._load_interpreter()
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 264, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/model.py", line 302, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/model.py", line 329, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/components.py", line 433, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/registry.py", line 181, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/utils/spacy_utils.py", line 130, in load
    nlp = cls.load_model(model_name)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/utils/spacy_utils.py", line 47, in load_model
    return spacy.load(spacy_model_name, disable=["parser"])
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 129, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 146, in load_model_from_link
    return cls.load(**overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 190, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 173, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/language.py", line 791, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 630, in from_disk
    reader(path / key)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/language.py", line 780, in <lambda>
    deserializers["vocab"] = lambda p: self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self)
  File "vocab.pyx", line 453, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 431, in spacy.vectors.Vectors.from_disk
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 625, in from_disk
    def from_disk(path, readers, exclude):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2019-07-04 11:49:39,773 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/run.py", line 180, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(nlu_model, endpoints.nlu)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 45, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 246, in __init__
    self._load_interpreter()
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 264, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/model.py", line 302, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/model.py", line 329, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/components.py", line 433, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/registry.py", line 181, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/utils/spacy_utils.py", line 130, in load
    nlp = cls.load_model(model_name)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/utils/spacy_utils.py", line 47, in load_model
    return spacy.load(spacy_model_name, disable=["parser"])
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 129, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 146, in load_model_from_link
    return cls.load(**overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 190, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 173, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/language.py", line 791, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 630, in from_disk
    reader(path / key)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/language.py", line 780, in <lambda>
    deserializers["vocab"] = lambda p: self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self)
  File "vocab.pyx", line 449, in spacy.vocab.Vocab.from_disk
  File "/usr/lib/python3.6/pathlib.py", line 898, in __truediv__
    def __truediv__(self, key):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2019-07-04 12:29:31,583 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2019-07-04 12:29:57,967 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2019-07-04 12:31:49,065 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2019-07-04 12:32:55,697 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2019-07-04 12:32:55,783 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/favicon.ico'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found
2019-07-04 12:34:44,962 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2019-07-04 12:35:12,981 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/model/parse'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /model/parse not found
2019-07-04 12:35:44,725 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/model/parse'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /model/parse not found
2019-07-09 10:33:32,354 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 11:24:07,249 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 11:31:58,165 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM4qzA'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:31:59,764 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM4rMA'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:01,580 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM4roe'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:03,000 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM4s8Q'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:05,570 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM4smt'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:10,586 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM4t_H'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:15,403 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM4vAW'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:20,419 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM4wOv'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:25,430 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM4xdH'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:30,446 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM4yrb'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:35,466 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM4-40'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:40,482 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM4_IP'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:45,494 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM50Wn'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:50,506 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM51l4'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:52,329 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM52BZ'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:53,310 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM52Qr'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:54,115 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM52dR'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:54,871 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM52pF'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:56,254 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM537w'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:32:58,187 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM53d6'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:33:00,940 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM54I8'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:33:04,994 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM55HT'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:33:05,792 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM55Ts'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:33:07,367 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM55sV'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:33:08,254 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM564F'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:33:09,774 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM56S6'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:33:12,110 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM570d'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:33:17,127 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM58Ez'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:33:22,147 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM59TP'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 11:33:27,164 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlM5Ahp'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 14:49:57,010 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 14:55:34,912 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 14:58:12,925 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 15:03:28,845 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 15:13:14,345 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 15:18:15,689 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 15:20:06,888 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 15:23:05,372 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 15:25:05,627 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 15:37:15,990 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 15:43:59,649 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 15:50:06,651 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 15:52:47,116 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 16:00:11,028 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 16:09:40,950 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 16:11:49,542 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/socket.io                                         OPTIONS                        handle_request
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/webhooks/socketio                                 GET                            socketio_webhook.health
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 16:11:49,617 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/run.py", line 180, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(nlu_model, endpoints.nlu)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 45, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 246, in __init__
    self._load_interpreter()
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 264, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/model.py", line 302, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/model.py", line 329, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/components.py", line 433, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/registry.py", line 181, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/utils/spacy_utils.py", line 130, in load
    nlp = cls.load_model(model_name)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/rasa/nlu/utils/spacy_utils.py", line 47, in load_model
    return spacy.load(spacy_model_name, disable=["parser"])
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 129, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 146, in load_model_from_link
    return cls.load(**overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 190, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 160, in load_model_from_path
    cls = get_lang_class(meta["lang"])
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/util.py", line 67, in get_lang_class
    module = importlib.import_module(".lang.%s" % lang, "spacy")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/lang/en/__init__.py", line 10, in <module>
    from .lemmatizer import LEMMA_RULES, LEMMA_INDEX, LEMMA_EXC, LOOKUP
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/spacy/lang/en/lemmatizer/__init__.py", line 4, in <module>
    from .lookup import LOOKUP  # noqa: F401
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 779, in get_code
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2019-07-09 16:13:19,538 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/socket.io                                         OPTIONS                        handle_request
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/webhooks/socketio                                 GET                            socketio_webhook.health
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 16:22:58,930 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-09 16:23:20,682 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7X9T'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:23:25,704 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7YNz'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:23:30,722 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7ZcN'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:23:35,737 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7aqm'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:23:40,754 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7c38'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:23:45,771 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7dHX'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:23:50,787 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7eVv'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:23:55,803 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7fkH'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:24:00,818 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7gyg'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:24:05,835 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7iB0'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:24:10,851 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7jPQ'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:24:15,866 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7kdo'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:24:20,881 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7ls9'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:24:25,893 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7n4X'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:24:30,909 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7oIo'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:24:35,923 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7pXA'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:24:40,941 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7qlY'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:24:45,958 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7rzx'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:24:50,974 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7tCK'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:24:55,991 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7uQi'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:25:01,007 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7vf4'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:25:06,025 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7wtT'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:25:11,041 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7y5t'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:25:16,058 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7zKF'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:25:21,073 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7-Ye'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:25:26,089 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN7_n0'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:25:31,104 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN80_N'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:25:36,122 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN82Dm'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:25:41,137 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MlN83S8'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /socket.io/ not found
2019-07-09 16:32:02,276 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-15 15:56:52,040 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-15 15:57:15,607 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/webhook'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /webhook not found
2019-07-15 15:59:57,431 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-15 16:00:52,173 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/webhook'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /webhook not found
2019-07-15 16:03:20,509 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/webhook'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /webhook not found
2019-07-15 16:06:07,686 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/rest/webhook'
Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /rest/webhook not found
2019-07-15 17:57:51,656 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/socket.io                                         GET                            handle_request
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/webhooks/socketio                                 GET                            socketio_webhook.health
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-16 14:31:08,844 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/socket.io                                         GET                            handle_request
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/webhooks/socketio                                 GET                            socketio_webhook.health
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-18 10:22:14,039 [ERROR]  Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1112, in uvloop.loop.Loop._create_server
  File "uvloop/handles/streamserver.pyx", line 58, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 95, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/server.py", line 745, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1684, in create_server
  File "uvloop/loop.pyx", line 1116, in uvloop.loop.Loop._create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5005): address already in use
2019-07-18 10:25:35,223 [ERROR]  Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1112, in uvloop.loop.Loop._create_server
  File "uvloop/handles/streamserver.pyx", line 58, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 95, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/server.py", line 745, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1684, in create_server
  File "uvloop/loop.pyx", line 1116, in uvloop.loop.Loop._create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5005): address already in use
2019-07-18 10:26:36,154 [ERROR]  Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1112, in uvloop.loop.Loop._create_server
  File "uvloop/handles/streamserver.pyx", line 58, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 95, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/edufraisse/Documents/secondchatbotenv/lib/python3.6/site-packages/sanic/server.py", line 745, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1684, in create_server
  File "uvloop/loop.pyx", line 1116, in uvloop.loop.Loop._create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5005): address already in use
